# Example configuration file for ytdl-sub config manager
# Copy to config.yaml and customize as needed

# Application-wide settings
application:
  # Use forward slashes for paths (works on both Windows and Unix)
  # On Windows: "D:/path/to/media" or use single quotes: 'D:\path\to\media'
  media-dir: "/path/to/your/media/directory"
  subs-file: "/path/to/subscriptions.yaml"
  run-in-container: true
  # Media source strategy to use (peloton, etc.)
  media-source: "peloton"

# Logging configuration
logging:
  level: "INFO"
  format: "standard"  # or "json" for structured logging

# GitHub integration (optional)
github:
  repo-url: "github.com/username/repo"
  token: "your-github-token"

# Peloton source configuration
peloton:
  username: "your-peloton-username"
  password: "your-peloton-password"
  class-limit-per-activity: 25
  activities: "cycling,yoga,strength"  # comma-separated list
  page-scrolls: 10
  
  # Dependency injection configuration for strategies
  directory_validation_strategies:
    - "src.io.peloton.activity_based_path_strategy:ActivityBasedPathStrategy"
  
  directory_repair_strategies:
    - "src.io.peloton.repair_5050_strategy:Repair5050Strategy"
  
  episode_parsers:
    - "src.io.peloton.episodes_from_disk:EpisodesFromDisk"
    - "src.io.peloton.episodes_from_subscriptions:EpisodesFromSubscriptions"
