# Debug configuration file for ytdl-sub config manager
# This file is used by VS Code debug configuration

# Application-wide settings
application:
  media-dir: "D:/labspace/tmp/test-media"
  #subs-file: "D:/labspace/ytdl-sub-config-manager/subscriptions.yaml"
  subs-file: "D:/labspace/ytdl-sub-config-manager/subscriptions.test.yaml"
  #subs-file: "D:/labspace/tmp/peloton-scrape-repo/kubernetes/main/apps/downloads/ytdl-sub/peloton/config/subscriptions.yaml" # GitHub Repo
  run-in-container: false  # Set to false for local debugging
  media-source: "peloton"  # Media source strategy to use
  # Number of days after which subscriptions are considered stale
  subscription-timeout-days: 30

# Logging configuration
logging:
  level: "DEBUG"
  format: "standard"  # Use "json" for structured logging
  # File logging for debugging
  file: "logs/debug.log"
  max_file_size_mb: 50   # Smaller files for debug
  backup_count: 5        # Fewer backups for debug

# GitHub integration (leave empty for local testing)
github:
  repo-url: ""
  token: ""
  temp-repo-dir: "D:/labspace/tmp/peloton-scrape-repo"
  auto-merge: false

# Peloton source configuration (will be overridden by environment variables in debug)
peloton:
  username: ""
  password: ""
  class-limit-per-activity: 15
  activities: "walking,strength,cycling"  # comma-separated list
  page-scrolls: 2
  dynamic-scrolling: true  # Enable dynamic scrolling based on class limits
  max-scrolls: 50  # Maximum scrolls when using dynamic scrolling
  
  # Dependency injection configuration for strategies
  directory_validation_strategies:
    - "src.io.peloton.activity_based_path_strategy:ActivityBasedPathStrategy"
  
  directory_repair_strategies:
    - "src.io.peloton.repair_5050_strategy:Repair5050Strategy"
    - "src.io.peloton.missing_instructor_repair_strategy:MissingInstructorRepairStrategy"
  
  episode_parsers:
    - "src.io.peloton.episodes_from_disk:EpisodesFromDisk"
    - "src.io.peloton.episodes_from_subscriptions:EpisodesFromSubscriptions"

# Web scraper configuration
scrapers:
  peloton.com:
    # Session management
    session_manager: "src.webscraper.session_manager:GenericSessionManager"
    login_strategy: "src.webscraper.peloton.login_strategy:PelotonLoginStrategy"
    
    # Scraping strategy
    scraper_strategy: "src.webscraper.peloton.scraper_strategy:PelotonScraperStrategy"
    
    # Scraping configuration
    headless: true
    container_mode: false  # Set to false for local debugging
    scroll_pause_time: 3.0
    login_wait_time: 15.0
    page_load_wait_time: 10.0