# Debug configuration file for ytdl-sub config manager
# This file is used by VS Code debug configuration

# Application-wide settings
application:
  media-dir: "/mnt/cephfs-hdd/data/media/peloton" # Live Server
  #media-dir: "/home/thaynes/tmp" # Empty Dir

  subs-file: "/tmp/peloton-scrape-repo/kubernetes/main/apps/downloads/ytdl-sub/peloton/config/subscriptions.yaml" # GitHub Repo
  #subs-file: "/home/thaynes/workspace/ytdl-sub-config-manager/subscriptions.test.yaml" # Local - In this repo
  
  run-in-container: false  # Set to false for local debugging
  media-source: "peloton"  # Media source strategy to use

# Logging configuration
logging:
  level: "DEBUG"
  format: "standard"  # Use "json" for structured logging
  # File logging for debugging
  file: "logs/debug.log"
  max_file_size_mb: 50   # Smaller files for debug
  backup_count: 5        # Fewer backups for debug

# GitHub integration (leave empty for local testing)
github:
  repo-url: ""
  token: ""
  temp-repo-dir: "/tmp/peloton-scrape-repo"

# Peloton source configuration (will be overridden by environment variables in debug)
peloton:
  username: ""
  password: ""

  # Full testing
  class-limit-per-activity: 25
  activities: "cycling,yoga,strength,meditation,cardio,stretching,running,walking,bootcamp,bike_bootcamp,rowing,row_bootcamp"  # All activities
  page-scrolls: 10

  # Isolated testing
  #class-limit-per-activity: 2
  #activities: "walking,cycling"
  #page-scrolls: 2
  
  # Dependency injection configuration for strategies
  directory_validation_strategies:
    - "src.io.peloton.activity_based_path_strategy:ActivityBasedPathStrategy"
  
  directory_repair_strategies:
    - "src.io.generic_repair_strategies.corrupted_video_filename_repair_strategy:CorruptedVideoFilenameRepairStrategy"
    - "src.io.generic_repair_strategies.corrupted_folder_deletion_strategy:CorruptedFolderDeletionStrategy"
    - "src.io.peloton.repair_5050_strategy:Repair5050Strategy"
    - "src.io.peloton.missing_instructor_repair_strategy:MissingInstructorRepairStrategy"
    - "src.io.peloton.bootcamp_folder_repair_strategy:BootcampFolderRepairStrategy"
    - "src.io.peloton.bootcamp_instructor_files_repair_strategy:BootcampInstructorFilesRepairStrategy"
    - "src.io.generic_repair_strategies.folder_filename_mismatch_repair_strategy:FolderFilenameMismatchRepairStrategy"
    - "src.io.generic_repair_strategies.empty_bootcamp_cleanup_strategy:EmptyBootcampCleanupStrategy"
    - "src.io.generic_repair_strategies.incomplete_episode_cleanup_strategy:IncompleteEpisodeCleanupStrategy"
  
  episode_parsers:
    - "src.io.peloton.episodes_from_disk:EpisodesFromDisk"
    - "src.io.peloton.episodes_from_subscriptions:EpisodesFromSubscriptions"

# Web scraper configuration
scrapers:
  peloton.com:
    # Session management
    session_manager: "src.webscraper.session_manager:GenericSessionManager"
    login_strategy: "src.webscraper.peloton.login_strategy:PelotonLoginStrategy"
    
    # Scraping strategy
    scraper_strategy: "src.webscraper.peloton.scraper_strategy:PelotonScraperStrategy"
    
    # Scraping configuration
    headless: true
    container_mode: false  # Set to false for local debugging
    scroll_pause_time: 3.0
    login_wait_time: 15.0
    page_load_wait_time: 10.0