name: Build and Push ytdl-sub Config Manager Image

on:
  push:
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/ytdl-sub-config-manager-build-and-push.yaml'
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

env:
  VERSION: "0.5.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage enforcement
        run: |
          pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=80 -v

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: success()
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: tags
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "stable_tags<<EOF" >> $GITHUB_OUTPUT
            echo "ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:latest" >> $GITHUB_OUTPUT
            echo "ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:${{ env.VERSION }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            # Extract branch name from ref (remove refs/heads/ prefix)
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            # Sanitize branch name for Docker tag (replace / with -)
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/\//-/g')
            echo "stable_tags=" >> $GITHUB_OUTPUT
            echo "dev_tag=ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
          fi
          echo "commit_tag=ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ steps.tags.outputs.stable_tags }}
            ${{ steps.tags.outputs.dev_tag }}
            ${{ steps.tags.outputs.commit_tag }}
