name: Build and Push ytdl-sub Config Manager Image

on:
  push:
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - '.github/workflows/ytdl-sub-config-manager-build-and-push.yaml'
  workflow_dispatch:
  
permissions:
  contents: read
  packages: write

env:
  VERSION: "0.1.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:latest
            ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/ytdl-sub-config-manager:${{ github.sha }}
